apiVersion: v1
kind: Service
metadata:
  name: api-logger-service
  namespace: esm
spec:
  type: NodePort
  selector:
    run: api-logger
  ports:
    - protocol: TCP
      port: 80            # ClusterIP port
      targetPort: 80      # Pod container port
      nodePort: 30080     # External port (can be 30000–32767)

