---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: mc-namespace
  name: mc-namespace
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mc-pod
  name: mc-pod
  namespace: mc-namespace
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
  - image: nginx:1-alpine
    name: mc-1
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
  - image: busybox
    name: mc-2
    command: ["sh", "-c"]
    args:
      - while true; do
          date >> /var/logs/shared/data.log;
          sleep 1;
        done
    volumeMounts:
      - name: shared-logs
        mountPath: /var/logs/shared
  - image: busybox 
    name: mc-3
    command: ["sh","-c"]
    args:
      - tail -f /var/logs/shared/data.log
    volumeMounts:
      - name: shared-logs
        mountPath: /var/logs/shared
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
