apiVersion: v1
kind: Pod
metadata:
  labels:
    run: firstpod
  name: firstpod
spec:
  containers:
  - image: nginx:alpine
    name: firstpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
