apiVersion: v1
kind: Namespace
metadata:
  name: front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: front-end
  labels:
    app: cart-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart-app
  template:
    metadata:
      labels:
        app: cart-app
    spec:
      containers:
        - name: cart
          image: cart-nginx:1.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  namespace: front-end
  name: cart-app
spec:
  type: NodePort
  selector:
    app: cart-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30050  # Uncomment to set a fixed port

