kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 30050
        hostPort: 30051
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 30050
        hostPort: 30052
        protocol: TCP